dbt_ml_case:
  target: prod
  outputs:
    test:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PSW') }}"

      database: analytics
      warehouse: compute_wh
      schema: dev
      
    prod:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PSW') }}"

      database: analytics
      warehouse: compute_wh
      schema: public
