version: 2

# Testing our raw data
seeds:
  - name: stg_weather_aus
    description: "Raw weather data set"
    columns:
      - name: MinTemp
        description: "Minimum temperature."
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -100
              max_value: 100
