version: 2

# Testing our raw data
seeds:
  - name: concrete
    description: "Cement features binned"
    columns:
      - name: age
        description: "Age of the cement."
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10
